// Module2_FrontendDevDivya/student-portal-react/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {
  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (
    <nav>
      <h2>Student Portal</h2>

      <Link to="/">Home</Link> |{" "}
      <Link to="/courses">Courses</Link> |{" "}
      <Link to="/profile">
        Profile ({enrolledCourses.length})
      </Link>
    </nav>
  );
}

export default Header;

// Module2_FrontendDevDivya/student-portal-vue/src/components/Header.vue
<template>
  <header>
    <h1>Student Portal</h1>

    <nav aria-label="Main navigation">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router'
</script>
